### ISSUE TITLE
Separate county name and zipcode

### ISSUE THREAD

**Issue by andkov** [dss-hmi/suicide-prevention-2019#3]
in #2, (`./manipulation/0-greeter-gls.R`) lines 135-136 https://github.com/dss-hmi/suicide-prevention-2019/blob/5879571bed189728c06c1fd52c062785a9ae17fe/manipulation/0-greeter-gls.R#L135 
we start splitting the column `county_zipcode` into two separate columns. 

![image](https://user-images.githubusercontent.com/2608073/57586540-1199cd80-74ac-11e9-919c-8ceb29fa4d86.png)
as you can see, regular expression governing this task need to be more flexible to accommodate variety of county spellings.
![image](https://user-images.githubusercontent.com/2608073/57586494-8587a600-74ab-11e9-96de-1171f7bbbaeb.png)

@Jodh , develop the regexes in this section of the code to properly parse `county_zipcode` into two separate columns.

**Comment by Jodh** [comment]
Testing [this](https://regex101.com/r/eQ1z0b/1) regex successfully extracts the name part for all three cases:
1.  Longname/12334
2.  Long. name/1234
3. Long name/1234

**Comment by andkov** [comment]
Sorry, @Jodh , I think I have solved this first. We have to use [this regex](https://regex101.com/r/NpHTYJ/1/) in order to capture some non-digits in the zipcode.
