### ISSUE TITLE
Obtain population estimates for FL at age year resolution

### ISSUE THREAD

**Issue by andkov** [dss-hmi/suicide-prevention-2019#34]
Explore the census.gov database to retrieve the population estimate for Florida for individual ages (e.g. 13, 14, etc), not just the age groups (e.g. 10 -14). 

Make sure that the data still contains the breakdown by:   
- sex  
- race + ethnicity  

Create a script `./manipulation/1-greeter-population-3.R` that output the product into `./data-unshared/derived/1-greeter-population-3.rds`

**Comment by mmmmtoasty19** [comment]
@andkov I have been looking for days for this kind of data and just can't find it.  Every data set I find is binned in the 5 year age groups.  While FLHealthcharts sort of has it, its just the 5 year groups divided by 5, which is clearly not accurate!

**Comment by andkov** [comment]
@mmmmtoasty19, I have reached out to @wibeasley , who might be able to help us: he says he did see such data at some point in the past.  Watch out for his contributions to the master branch.

**Comment by andkov** [comment]
@mmmmtoasty19 , see https://wonder.cdc.gov/
specifically, https://wonder.cdc.gov/bridged-race-population.html. It has the data we need.
