### ISSUE TITLE
Demographic display

### ISSUE THREAD

**Issue by andkov** [dss-hmi/suicide-prevention-2019#9]
@mmmmtoasty19 , please create a report describing the demographic trends in Florida over the last 10 years ( 2006 - 2017),, so that we could evaluate the difference in age, sex, race+ethnicity.

Please store the progress in `./analysis/population-estimates/`

**Comment by mmmmtoasty19** [comment]
@andkov 
Please see my latest commit to see my start.   I have begun playing with Shiny and wanted to do it as a RMD document, however it appears that Shiny and Knitr aren't playing well together.  I am unable to set the RMD document to read the chunk, as it wont set the root to the root, instead the root stays wherever the Shiny doc is.   
Would it be best to make a separate app for Shiny or do it as a stand alone doc?

**Comment by andkov** [comment]
@mmmmtoasty19 , I like what you did, I actually don't remember if I every integrating RShiny app into knitted report. And as you have noticed, we cannot save an HTML of it (so we can serve it via something like raw.githack.com like we can static reports, e.g. .[/analysis/population-estimates/population-estimates.html](https://raw.githack.com/dss-hmi/suicide-prevention-2019/dev-kyle/analysis/population-estimates/population-estimates.html) ).
This means that the readers of the report will have to launch it locally on their machines, or we need to publish it to a public RShiny Server. Either way, I would create a dedicated Shiny App (UI + Server). 

Alternatively, I really like what @wibeasley has done with a multitab HTML that integrate plotly. Please study his [dashboard](https://raw.githack.com/wibeasley/RAnalysisSkeleton/master/analysis/dashboard-1/dashboard-1.html) example, which you can replicate by cloning https://github.com/wibeasley/RAnalysisSkeleton repo. 

I think RShiny App will help us explore relevant patterns and settle on the story we want to tell, while the dashboard will help us focus readers' attention on a handful of useful display that unfold the narrative.  So I would start with a tabs Shiny App, that offers a varieties of view into the data (we already have 2: counts over time by ethnic groups and age distribution on a given year).

**Comment by wibeasley** [comment]
Thanks @andkov.  Depending on your audience, this new chapter might help: https://ouhscbbmc.github.io/data-science-practices-1/example-dashboard.html

**Comment by andkov** [comment]
Thanks, @wibeasley! Your book is taking shape very nicely! I am fervid apostle of your reproducible analysis approach, which I am currently implementing in my class on Health Care Analytics (https://github.com/dss-hmi/hsa6752-spring-2020) . Kyle (@mmmmtoasty19 ) is taking the course right now, as well as collaborating with me on several projects that will require RShiny.

**Comment by andkov** [comment]
this issue has transformed into #10
